import { createApp } from 'vue';
import { createPinia } from 'pinia';
import persistentState from 'pinia-plugin-persistedstate';
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/reset.css';
import echarts from 'vue-echarts';
import 'echarts';
import router from './router';
import App from './App.vue';
import '@/styles/index.scss';
import '@/assets/iconfont/iconfont.css';
import '@/router/permission.js';
// import '@/utils/check-update';
const pinia = createPinia();
pinia.use(persistentState);
const app = createApp(App);
app.component('vue-echarts', echarts);
app.use(Antd);
app.use(pinia);
app.use(router);
app.mount('#app');
